apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaos-test-dummy
  labels:
    app: busybox
    job-type: cthulhu
    ctt-type: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        job-type: cthulhu
        ctt-type: test
    spec:
      containers:
      - name: busybox-one
        image: busybox
        args:
        - sh
        stdin: true
        tty: true
      - name: busybox-two
        image: busybox
        args:
        - sh
        stdin: true
        tty: true

